### ISSUE TITLE
$unfurl Presentation Improvements

### ISSUE THREAD

**Issue by necopinus** [The-Yak-Collective/onboarding_robot#27]
[A couple of interesting ideas](https://discordapp.com/channels/692111190851059762/739204942417494047/818835097519652865) came up around $unfurl:

It might make sense to change the unfurl from just a more-or-less straight re-post to an embed (like the menu system uses). Advantages:

- Makes unfurls stand out a little more.
- Perhaps allows us to embed the original poster's avatar, etc.
- Would enable us to embed a link to the original post in the unfurl.
- Could add a note about who requested the unfurl.

The last two of these points would then allow us to have the bot _delete_ the original `$unfurl` command after generating the embed, which will make things look cleaner in the channel.

Main disadvantages:

- This is a major rewrite of how the functionality is handled.
- Posts are limited to 2000 characters, but embed fields are limited to 1024 characters, so this could cause some problems. It looks like embed _descriptions_ have a 2048 character limit though, so perhaps this can be used? (I'm having trouble finding official documentation about embeds though, and am running off [the documentation for Discord.js](https://discordjs.guide/popular-topics/embeds.html).)

**Comment by tilnow** [comment]
i actually want message to look as normal as possible. still considering option of auto-delete of original unfurl message
